import Ember from 'ember';

let repos = [{
      "id": 72354151,
      "name": "object-version-reconstruction",
      "full_name": "anand-sundaram/object-version-reconstruction",
      "owner": {
        "login": "anand-sundaram",
        "id": 7693514,
        "avatar_url": "https://avatars.githubusercontent.com/u/7693514?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/anand-sundaram",
        "html_url": "https://github.com/anand-sundaram",
        "followers_url": "https://api.github.com/users/anand-sundaram/followers",
        "following_url": "https://api.github.com/users/anand-sundaram/following{/other_user}",
        "gists_url": "https://api.github.com/users/anand-sundaram/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/anand-sundaram/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/anand-sundaram/subscriptions",
        "organizations_url": "https://api.github.com/users/anand-sundaram/orgs",
        "repos_url": "https://api.github.com/users/anand-sundaram/repos",
        "events_url": "https://api.github.com/users/anand-sundaram/events{/privacy}",
        "received_events_url": "https://api.github.com/users/anand-sundaram/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/anand-sundaram/object-version-reconstruction",
      "description": "Query the state of objects in a CSV file by timestamp",
      "fork": false,
      "url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction",
      "forks_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/forks",
      "keys_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/teams",
      "hooks_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/hooks",
      "issue_events_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/issues/events{/number}",
      "events_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/events",
      "assignees_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/assignees{/user}",
      "branches_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/branches{/branch}",
      "tags_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/tags",
      "blobs_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/languages",
      "stargazers_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/stargazers",
      "contributors_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/contributors",
      "subscribers_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/subscribers",
      "subscription_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/subscription",
      "commits_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/contents/{+path}",
      "compare_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/merges",
      "archive_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/downloads",
      "issues_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/issues{/number}",
      "pulls_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/labels{/name}",
      "releases_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/releases{/id}",
      "deployments_url": "https://api.github.com/repos/anand-sundaram/object-version-reconstruction/deployments",
      "created_at": "2016-10-30T14:25:50Z",
      "updated_at": "2016-10-30T14:25:50Z",
      "pushed_at": "2016-10-30T14:25:50Z",
      "git_url": "git://github.com/anand-sundaram/object-version-reconstruction.git",
      "ssh_url": "git@github.com:anand-sundaram/object-version-reconstruction.git",
      "clone_url": "https://github.com/anand-sundaram/object-version-reconstruction.git",
      "svn_url": "https://github.com/anand-sundaram/object-version-reconstruction",
      "homepage": null,
      "size": 0,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": null,
      "has_issues": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 0,
      "mirror_url": null,
      "open_issues_count": 0,
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master",
      "score": 5.0426793
    }];

export default Ember.Route.extend({
	model() {
		return repos;
	}
});
